using Newtonsoft.Json;

namespace MonoLDtk.Shared.LDtkProject.LDtkInstance;

internal class LayerInstance
{
    /// <summary>
    /// Grid-based height
    /// </summary>
    [JsonProperty("__cHei")]
    internal long CHei { get; set; }

    /// <summary>
    /// Grid-based width
    /// </summary>
    [JsonProperty("__cWid")]
    internal long CWid { get; set; }

    /// <summary>
    /// Grid size
    /// </summary>
    [JsonProperty("__gridSize")]
    internal long GridSize { get; set; }

    /// <summary>
    /// Layer definition identifier
    /// </summary>
    [JsonProperty("__identifier")]
    internal string Identifier { get; set; }

    /// <summary>
    /// Layer opacity as Float [0-1]
    /// </summary>
    [JsonProperty("__opacity")]
    internal double Opacity { get; set; }

    /// <summary>
    /// Total layer X pixel offset, including both instance and definition offsets.
    /// </summary>
    [JsonProperty("__pxTotalOffsetX")]
    internal long PxTotalOffsetX { get; set; }

    /// <summary>
    /// Total layer Y pixel offset, including both instance and definition offsets.
    /// </summary>
    [JsonProperty("__pxTotalOffsetY")]
    internal long PxTotalOffsetY { get; set; }

    /// <summary>
    /// The definition UID of corresponding Tileset, if any.
    /// </summary>
    [JsonProperty("__tilesetDefUid")]
    internal long? TilesetDefUid { get; set; }

    /// <summary>
    /// The relative path to corresponding Tileset, if any.
    /// </summary>
    [JsonProperty("__tilesetRelPath")]
    internal string TilesetRelPath { get; set; }

    /// <summary>
    /// Layer type (possible values: IntGrid, Entities, Tiles or AutoLayer)
    /// </summary>
    [JsonProperty("__type")]
    internal string Type { get; set; }

    /// <summary>
    /// An array containing all tiles generated by Auto-layer rules. The array is already sorted
    /// in display order (ie. 1st tile is beneath 2nd, which is beneath 3rd etc.).<br/><br/>
    /// Note: if multiple tiles are stacked in the same cell as the result of different rules,
    /// all tiles behind opaque ones will be discarded.
    /// </summary>
    [JsonProperty("autoLayerTiles")]
    internal TileInstance[] AutoLayerTiles { get; set; }

    [JsonProperty("entityInstances")]
    internal EntityInstance[] EntityInstances { get; set; }

    [JsonProperty("gridTiles")]
    internal TileInstance[] GridTiles { get; set; }

    /// <summary>
    /// Unique layer instance identifier
    /// </summary>
    [JsonProperty("iid")]
    internal Guid Iid { get; set; }

    /// <summary>
    /// **WARNING**: this deprecated value is no longer exported since version 1.0.0  Replaced
    /// by: `intGridCsv`
    /// </summary>
    [JsonProperty("intGrid")]
    internal IntGridValueInstance[] IntGrid { get; set; }

    /// <summary>
    /// A list of all values in the IntGrid layer, stored in CSV format (Comma Separated
    /// Values).<br/>  Order is from left to right, and top to bottom (ie. first row from left to
    /// right, followed by second row, etc).<br/>  `0` means "empty cell" and IntGrid values
    /// start at 1.<br/>  The array size is `__cWid` x `__cHei` cells.
    /// </summary>
    [JsonProperty("intGridCsv")]
    internal long[] IntGridCsv { get; set; }

    /// <summary>
    /// Reference the Layer definition UID
    /// </summary>
    [JsonProperty("layerDefUid")]
    internal long LayerDefUid { get; set; }

    /// <summary>
    /// Reference to the UID of the level containing this layer instance
    /// </summary>
    [JsonProperty("levelId")]
    internal long LevelId { get; set; }

    /// <summary>
    /// An Array containing the UIDs of optional rules that were enabled in this specific layer
    /// instance.
    /// </summary>
    [JsonProperty("optionalRules")]
    internal long[] OptionalRules { get; set; }

    /// <summary>
    /// This layer can use another tileset by overriding the tileset UID here.
    /// </summary>
    [JsonProperty("overrideTilesetUid")]
    internal long? OverrideTilesetUid { get; set; }

    /// <summary>
    /// X offset in pixels to render this layer, usually 0 (IMPORTANT: this should be added to
    /// the `LayerDef` optional offset, so you should probably prefer using `__pxTotalOffsetX`
    /// which contains the total offset value)
    /// </summary>
    [JsonProperty("pxOffsetX")]
    internal long PxOffsetX { get; set; }

    /// <summary>
    /// Y offset in pixels to render this layer, usually 0 (IMPORTANT: this should be added to
    /// the `LayerDef` optional offset, so you should probably prefer using `__pxTotalOffsetX`
    /// which contains the total offset value)
    /// </summary>
    [JsonProperty("pxOffsetY")]
    internal long PxOffsetY { get; set; }

    /// <summary>
    /// Random seed used for Auto-Layers rendering
    /// </summary>
    [JsonProperty("seed")]
    internal long Seed { get; set; }

    /// <summary>
    /// Layer instance visibility
    /// </summary>
    [JsonProperty("visible")]
    internal bool Visible { get; set; }
}
