namespace MonoLDtk.Shared;

public enum AllowedRefs { Any, OnlySame, OnlySpecificEntity, OnlyTags };
public enum BgPos { Contain, Cover, CoverDirty, Repeat, Unscaled };
public enum Checker { Horizontal, None, Vertical };
public enum EditorDisplayMode { ArrayCountNoLabel, ArrayCountWithLabel, EntityTile, Hidden, LevelTile, NameAndValue, PointPath, PointPathLoop, PointStar, Points, RadiusGrid, RadiusPx, RefLinkBetweenCenters, RefLinkBetweenPivots, ValueOnly };
public enum EditorDisplayPos { Above, Beneath, Center };
public enum EditorLinkStyle { ArrowsLine, CurvedArrow, DashedLine, StraightArrow, ZigZag };
public enum EmbedAtlas { LdtkIcons };
public enum Flag { DiscardPreCsvIntGrid, ExportPreCsvIntGridFormat, IgnoreBackupSuggest, MultiWorlds, PrependIndexToLevelFileNames, UseMultilinesType };
public enum IdentifierStyle { Capitalize, Free, Lowercase, Uppercase };
public enum ImageExportMode { LayersAndLevels, None, OneImagePerLayer, OneImagePerLevel };
public enum LimitBehavior { DiscardOldOnes, MoveLastOne, PreventAdding };
public enum LimitScope { PerLayer, PerLevel, PerWorld };
public enum When { AfterLoad, AfterSave, BeforeSave, Manual };
public enum WorldLayout { Free, GridVania, LinearHorizontal, LinearVertical };
public enum RenderMode { Cross, Ellipse, Rectangle, Tile };
public enum TextLanguageMode { LangC, LangHaxe, LangJs, LangJson, LangLog, LangLua, LangMarkdown, LangPython, LangRuby, LangXml };
public enum TileMode { Single, Stamp };
public enum TileRenderMode { Cover, FitInside, FullSizeCropped, FullSizeUncropped, NineSlice, Repeat, Stretch };
public enum TypeEnum { AutoLayer, Entities, IntGrid, Tiles };